# Generated by Django 5.1.6 on 2025-03-05 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Marks cannot be negative'), django.core.validators.MaxValueValidator(100, message='Marks cannot exceed 100')])),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel Data',
                'verbose_name_plural': 'Excel Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
